# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

# https://www.youtube.com/watch?v=IvxWDFb-fSs

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_test_deploy:
    name: Build, Test and Deploy 
    runs-on: ubuntu-latest

    permissions: 
      contents: read
      pull-requests: read

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install AWS Lambda Tools
      run: go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    
    - name: Go Build
      run: go build -v ./...
  
    - name: Go Test
      run: go test -v ./...
  
    - name: CDK Deploy
      run: cdk deploy --all --require-approval never

    - name: Purge Queues
      run: go run ./cli/purgequeues/purgequeues.go SQS1Stack-TestQueue

    - name: Purge Tables
      run: go run ./cli/purgetables/purgetables.go TestMessageTable

    - name: Purge Lambdas
      run: go run ./cli/purgelambdas/purgelambdas.go SQS1Stack-

